services:
  - type: web
    name: legends-tunisia-stats
    runtime: docker
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: LEVELS_BOT_TOKEN
        sync: false

  - type: web
    name: discord-mod-bot
    runtime: docker
    dockerfilePath: ./discord-mod-bot/Dockerfile
    dockerContext: ./discord-mod-bot
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: DISCORD_TOKEN
        sync: false
